controller_list:
  - name: main_group_controller
    joints:
      - base_joint
      - shoulder_joint
      - elbow_joint
      - pitch_joint
      - roll_joint
  - name: gripp_group_controller
    joints:
      - pad1_joint
      - pad2_joint
